# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20160513_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subunittosubject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subunittosubject',
            name='subunit',
        ),
        migrations.AddField(
            model_name='subject',
            name='subunits',
            field=models.ManyToManyField(to='testapp.Subunit'),
        ),
        migrations.DeleteModel(
            name='SubunitToSubject',
        ),
    ]
