# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20160513_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subunit',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.ForumSection', unique=True),
        ),
        migrations.AlterField(
            model_name='subunit',
            name='upper_subunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lower', to='testapp.Subunit'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.Subunit'),
        ),
    ]
